# Generated by Django 5.0.2 on 2024-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspage', '0003_order_address_order_contact_no_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
